let largura = prompt("Volume da largura", 0);//voce altera na pagina
let altura = prompt("Volume da altura", 0); //voce altera na pagina
let comprimento = prompt("Volume de comprimento", 0); //voce altera na pagina
let volume = largura * altura * comprimento; 
alert(`volume calculado de tudo = ${volume}`);
console.log(`volume da largura = ${largura}`);
console.log(`volume da altura = ${altura}`);
console.log(`volume de comprimento = ${comprimento}`);
console.log(`volume calculado de tudo = ${volume}`);